CONFIG_BUZZER_ENABLED=n

CONFIG_PROTOCOL_LOG_LEVEL_INF=y
CONFIG_MINMEA_LOG_LEVEL_INF=y
CONFIG_APP_ACTUATION_LOG_LEVEL_INF=y
CONFIG_APP_FILTER_LOG_LEVEL_INF=y
CONFIG_APP_FLIGHT_LOG_LEVEL_INF=y
CONFIG_APP_MAIN_LOG_LEVEL_INF=y
CONFIG_APP_SENSORS_LOG_LEVEL_INF=y
CONFIG_APP_COMMUNICATION_LOG_LEVEL_INF=y
CONFIG_APP_COMMANDS_LOG_LEVEL_INF=y
CONFIG_APP_AERODYNAMICS_LOG_LEVEL_INF=y

#CONFIG_DUMMYSENSOR_AESIR=n # bad venting
#CONFIG_DUMMYSENSOR_ASAT=y # bad venting
#CONFIG_DUMMYSENSOR_ASTG=y # mid venting, liquid
#CONFIG_DUMMYSENSOR_BRISTOL=y # mid venting, liquid
#CONFIG_DUMMYSENSOR_FARADAY=y # good venting, liquid
#CONFIG_DUMMYSENSOR_RED=y # very good venting